# Path config
raw_dataset_path: data/raw/hr_employee_attrition.csv
raw_dataset_collected_path: data/processed/raw_dataset.pkl
train_set_path:
  x: data/processed/x_train.pkl
  y: data/processed/y_train.pkl
test_set_path:
  x: data/processed/x_test.pkl
  y: data/processed/y_test.pkl
valid_set_path:
  x: data/processed/x_valid.pkl
  y: data/processed/y_valid.pkl
train_set_feng_path:
  x: data/processed/x_train_feng.pkl
  y: data/processed/y_train_feng.pkl
test_set_feng_path:
  x: data/processed/x_test_feng.pkl
  y: data/processed/y_test_feng.pkl
valid_set_feng_path:
  x: data/processed/x_valid_feng.pkl
  y: data/processed/y_valid_feng.pkl

production_model_path: models/production_model.pkl
training_log_path: log/training_log.json

ohe_Department_path: models/ohe_Department.pkl
ohe_JobRole_path: models/ohe_JobRole.pkl
ohe_Gender_path: models/ohe_Gender.pkl
ohe_OverTime_path: models/ohe_OverTime.pkl
le_encoder_path: models/le_encoder.pkl

# Debug config
print_debug: true

# List of selected column config 
int64_columns:
- JobLevel
- Age
- DistanceFromHome
- YearsAtCompany
- YearsInCurrentRole
- YearsSinceLastPromotion
- YearsWithCurrManager
- MonthlyIncome
- MonthlyRate
- EnvironmentSatisfaction
- JobSatisfaction
- WorkLifeBalance
- PerformanceRating

object_columns:
- Attrition
- Department
- JobRole
- Gender
- OverTime

# Object columns range
Attrition_range:
- 'Yes'
- 'No'

Department_range:
- Sales
- Research & Development
- Human Resources
Gender_range:
- Female
- Male
JobRole_range:
- Sales Executive
- Research Scientist
- Laboratory Technician
- Manufacturing Director
- Healthcare Representative
- Manager
- Sales Representative
- Research Director
- Human Resources
OverTime_range:
- 'Yes'
- 'No'

# Int64 column range
Age_range:
  max: 60
  min: 18
DistanceFromHome_range:
  max: 50
  min: 0
EnvironmentSatisfaction_range:
  max: 4
  min: 1
JobLevel_range:
  max: 5
  min: 1
JobSatisfaction_range:
  max: 4
  min: 1
MonthlyIncome_range:
  max: 49999
  min: 1000
MonthlyRate_range:
  max: 49999
  min: 1000
PerformanceRating_range:
  max: 4
  min: 1
WorkLifeBalance_range:
  max: 4
  min: 1
YearsAtCompany_range:
  max: 40
  min: 0
YearsInCurrentRole_range:
  max: 18
  min: 0
YearsSinceLastPromotion_range:
  max: 15
  min: 0
YearsWithCurrManager_range:
  max: 17
  min: 0

missing_value_handling:
  Age: 37
  Department: Research & Development
  DistanceFromHome: 9
  EnvironmentSatisfaction: 3
  Gender: Male
  JobLevel: 2
  JobRole: Sales Executive
  JobSatisfaction: 3
  MonthlyIncome: 6548
  MonthlyRate: 14465
  OverTime: 'No'
  PerformanceRating: 3
  WorkLifeBalance: 3
  YearsAtCompany: 7
  YearsInCurrentRole: 4
  YearsSinceLastPromotion: 2
  YearsWithCurrManager: 4

predictor_columns:
- JobLevel
- Age
- DistanceFromHome
- YearsAtCompany
- YearsInCurrentRole
- YearsWithCurrManager
- MonthlyIncome
- EnvironmentSatisfaction
- JobSatisfaction
- WorkLifeBalance
- PerformanceRating
- Department
- JobRole
- OverTime

target_column: Attrition