# Path config
raw_dataset_path: data/raw/hr_employee_attrition.csv
raw_dataset_collected_path: data/processed/raw_dataset.pkl
train_set_path:
  x: data/processed/x_train.pkl
  y: data/processed/y_train.pkl
test_set_path:
  x: data/processed/x_test.pkl
  y: data/processed/y_test.pkl
valid_set_path:
  x: data/processed/x_valid.pkl
  y: data/processed/y_valid.pkl

# Debug config
print_debug: true

# List of selected column config 
int64_columns:
- JobLevel
- Age
- DistanceFromHome
- YearsAtCompany
- YearsInCurrentRole
- YearsSinceLastPromotion
- YearsWithCurrManager
- MonthlyIncome
- MonthlyRate
- EnvironmentSatisfaction
- JobSatisfaction
- WorkLifeBalance
- PerformanceRating

object_columns:
- Attrition
- Department
- JobRole
- Gender
- OverTime

# Object columns range
Attrition_range:
- 'Yes'
- 'No'

Department_range:
- Sales
- Research & Development
- Human Resources
Gender_range:
- Female
- Male
JobRole_range:
- Sales Executive
- Research Scientist
- Laboratory Technician
- Manufacturing Director
- Healthcare Representative
- Manager
- Sales Representative
- Research Director
- Human Resources
OverTime_range:
- 'Yes'
- 'No'

# Int64 column range
Age_range:
  max: 60
  min: 18
DistanceFromHome_range:
  max: 50
  min: 0
EnvironmentSatisfaction_range:
  max: 4
  min: 1
JobLevel_range:
  max: 5
  min: 1
JobSatisfaction_range:
  max: 4
  min: 1
MonthlyIncome_range:
  max: 49999
  min: 1000
MonthlyRate_range:
  max: 49999
  min: 1000
PerformanceRating_range:
  max: 4
  min: 1
WorkLifeBalance_range:
  max: 4
  min: 1
YearsAtCompany_range:
  max: 40
  min: 0
YearsInCurrentRole_range:
  max: 18
  min: 0
YearsSinceLastPromotion_range:
  max: 15
  min: 0
YearsWithCurrManager_range:
  max: 17
  min: 0


predictor_columns:
- Department
- JobRole
- Gender
- JobLevel
- Age
- YearsAtCompany
- YearsInCurrentRole
- YearsSinceLastPromotion
- YearsWithCurrManager
- MonthlyIncome
- EnvironmentSatisfaction
- JobSatisfaction
- WorkLifeBalance
- PerformanceRating

target_column:
- Attrition

